### ISSUE TITLE
Test: Does explicit export of an import-derived symbol work in mutual dependency?

### ISSUE THREAD

**Issue by jj101k** [jj101k/import-export#8]
bar.js:

```
import {foo} from "./foo"
export var bar = foo + 1
```

foo.js:

```
import "./bar" // for whatever reason
export var foo = 41
```

My suspicion is that this does not work at all. In most patterns this isn't a large problem because evaluation of deferred import is at runtime not load time.

**Comment by jj101k** [comment]
Transform-wise, that would be:

```
module.exports = {}
import("./foo").then(ns => {
    var foo = ns.foo
    module.exports.bar = var bar = foo + 1
})
```

```
module.exports = {}
import("./bar").then(ns => {
    module.exports.foo = var foo = 41
})
```

...but `foo` absolutely must be resolved before `bar` is yet somehow also after `bar` is.

**Comment by jj101k** [comment]
Could provide multiple promise scenarios to work around this and "step through" mutual dependencies, which would resolve the pattern:

```
import {foo} from "./foo"
export var bar = 1
export var baz = foo + 1
```

```
import {bar} from "./bar"
export var foo = 41
export var foz = bar + 1
```

However, the supplied pattern would require that evaluation on foo.js is complete - likewise the same if the import-derived expression is first in either of them.

**Comment by jj101k** [comment]
This would work more reliably if you could rearrange the AST, although you could still produce an infinite include loop.

**Comment by jj101k** [comment]
Will leave this until/unless there's a real-world problem to compare - which may be after module support goes live for Node: https://nodejs.org/api/esm.html

**Comment by jj101k** [comment]
Was just going to test this, and hit another bug:

```
const eximportBridge=require("eximport-bridge").prepareBridge(["bar"]);module.exports=eximportBridge.ns;eximportBridge.execute(function* () {with(require("./foo")._bridge.named({"foo":"foo"})){;yield
```

`TypeError: Cannot read property 'named' of undefined`

**Comment by jj101k** [comment]
This now produces:

```
> node test.js

.../eximport/node_modules/eximport-bridge/index.js:166
            g = this.generator.next()
                               ^

TypeError: Generator is already running
    at Generator.next (<anonymous>)
    at EximportBridge.finish (.../eximport/node_modules/eximport-bridge/index.js:166:32)
    at .../eximport/test/export-import-derived-mutual/foo.js:1:186
    at Generator.next (<anonymous>)
    at EximportBridgeNamespace.get [as foo] (.../eximport/node_modules/eximport-bridge/index.js:60:60)
    at Object.get (.../eximport/node_modules/eximport-bridge/index.js:184:39)
    at .../eximport/test/export-import-derived-mutual/bar.js:2:11
    at Generator.next (<anonymous>)
    at EximportBridgeNamespace.get [as bar] (.../eximport/node_modules/eximport-bridge/index.js:60:60)
    at Object.<anonymous> (.../eximport/test/export-import-derived-mutual/t.js:3:18)
npm ERR! Test failed.  See above for more details.
```

That's expected as this is a hard mutual dependency
